alpaca-finance/alpaca-v2-money-market

solidity/contracts/reader/MoneyMarketReader.sol

[main][fix] market price info reader

---

.env.example
foundry.toml

[main][chore] add bsc scan config

---

.mainnet.json

Update addresses in BNB mainnet
Transparency

[main][chore] Update mainnet addresses

---

solidity/contracts/money-market/MoneyMarketDiamond.sol
solidity/tests/money-market/accrue-interest/MoneyMarket_AccrueInterest_Borrow.t.sol
solidity/tests/money-market/liquidation/MoneyMarket_Liquidation_IbRepurchase.t.sol

- new foundry version revert when called stopPrank without startPrank

[main][fix] test fail

---

package.json
script/deployments/MoneyMarket/config/WithdrawProtocolReserves.s.sol

[main][chore] withdraw protocol reserve script

---

.mainnet.json
package.json
script/deployments/AlpacaV2Oracle/config/SetPools.s.sol
script/deployments/AlpacaV2Oracle/config/SetTokenConfig.s.sol
script/deployments/AlpacaV2Oracle/deploy/AlpacaV2Oracle.s.sol
script/deployments/MiniFL/config/SetAlpacaPerSecond.s.sol
script/deployments/MiniFL/config/SetPool.s.sol
script/deployments/MiniFL/config/SetWhitelistedCallers.s.sol
script/deployments/MiniFL/script/MassUpdatePools.s.sol
script/deployments/MoneyMarket/config/SetLiquidatorsOk.s.sol
solidity/contracts/miniFL/interfaces/IMiniFL.sol

[main][deploy] money market

---

solidity/contracts/money-market/facets/FlashloanFacet.sol

Add more descriptive comment
To understand how contract works better

[main][chore] Improve comment in Flashloan facet

---

solidity/contracts/account-manager/MoneyMarketAccountManager.sol
solidity/contracts/interfaces/IMoneyMarketAccountManager.sol
solidity/contracts/money-market/facets/FlashloanFacet.sol
solidity/tests/money-market/account-manager/MoneyMarket_AccountManager.t.sol

Add native token support for staking native ibToken
Support better UX in frontend

[main][feat]: Add native token support for staking in AccountManager

---

script/deployments/libraries/LibMoneyMarketDeployment.sol
solidity/contracts/money-market/facets/ViewFacet.sol
solidity/contracts/money-market/interfaces/IViewFacet.sol

- Add whitelist check (liquidationStrat, liquidators, risk manager, account manager and operators) in view facet
- Add getter of flash loan treasury

[main][feat] Add getter of whitelist and flash loan treasury

---

.mainnet.json

[main][chore] new mm reader address

---

solidity/contracts/upgradable/AdminUpgradeabilityProxy.sol
solidity/contracts/upgradable/ProxyAdmin.sol
yarn.lock

[main][chore] Fix dependcies

---

package.json
script/deployments/MoneyMarket/deploy/LiquidationFacet.s.sol
solidity/contracts/money-market/libraries/LibMoneyMarket01.sol

[main][chore] emit account in write off debt event

---

package.json
script/deployments/MoneyMarket/config/SetTokenMaximumCapacities.s.sol

[main][feat] set token max capacities script

---

.mainnet.json
script/deployments/MiniFL/config/SetPoolRewarders.s.sol
script/deployments/Rewarder/config/AddPool.s.sol
script/deployments/Rewarder/config/SetRewardPerSecond.s.sol
script/deployments/Rewarder/deploy/Rewarder.s.sol

[main][deploy] Open HIGH market

---

script/deployments/PancakeswapV3IbTokenLiquidationStrategy/config/SetPaths.s.sol

[main][chore] setPath 3 hops

---

.mainnet.json
script/BaseScript.sol
script/deployments/PathReader/config/SetPCSV3Paths.s.sol
script/deployments/PathReader/config/SetV2Paths.s.sol
script/deployments/PathReader/deploy/PCSV3PathReader.s.sol
script/deployments/PathReader/deploy/UniSwapV2LikePathReader.s.sol
solidity/contracts/reader/PCSV2PathReader.sol
solidity/contracts/reader/PCSV3PathReader.sol
solidity/contracts/reader/UniSwapV2LikePathReader.sol
solidity/contracts/reader/interfaces/IUniSwapV2PathReader.sol
solidity/contracts/reader/interfaces/IUniSwapV3PathReader.sol
solidity/contracts/smart-treasury/SmartTreasury.sol
solidity/tests/path-reader/PCSV3PathReader.t.sol
solidity/tests/path-reader/UniSwapV2LikePathReader.t.sol
solidity/tests/smart-treasury/BaseFork.sol
solidity/tests/smart-treasury/SmartTreasury_Distribute.t.sol

- add v2 swap in distribution
- add v2 test in distribution
- Some tokens might have not liquidity on v3. So we need to check v2 liquidity first.
- If there is no liquidity on both v2 and v3. Then we skip current token and distribute next token.

[main][fix] distribution support v2 liquidity

---

solidity/contracts/smart-treasury/SmartTreasury.sol

[main][feat] Optimize smart treasury

---

solidity/contracts/smart-treasury/SmartTreasury.sol
solidity/tests/smart-treasury/SmartTreasury_Distribute.t.sol
solidity/tests/smart-treasury/SmartTreasury_SetConfigs.t.sol

[main][fix] smart treasury change setter from whitelisted to onlyOwner

---

solidity/contracts/reader/PCSV3PathReader.sol
solidity/contracts/reader/UniSwapV2LikePathReader.sol
solidity/contracts/smart-treasury/SmartTreasury.sol
solidity/tests/path-reader/PCSV3PathReader.t.sol
solidity/tests/path-reader/UniSwapV2LikePathReader.t.sol
solidity/tests/smart-treasury/SmartTreasury_Distribute.t.sol
solidity/tests/smart-treasury/SmartTreasury_SetConfigs.t.sol

- Change from sum of alloc point to guarantee sum to be max bps (10000)
Save gas during allocation

[main][feat] Change alloc to bps in Smart Treasury

---

.mainnet.json

- update cake, xrp market to mainnet
- To sync with alpaca v2 interface
- defillama use data from here

[main][chore] update mainnet.json file

---

solidity/contracts/oracle/AlpacaV2Oracle02.sol
solidity/contracts/oracle/interfaces/IAlpacaV2Oracle02.sol

Add isStable function to AlpacaV2Oracle02
It's used in MoneyMarketReader contract. Missing the function will break the UI

[main][feat]: add isStable to AlpacaV2Oracle02

---

solidity/contracts/money-market/facets/AdminFacet.sol
solidity/contracts/money-market/interfaces/IAlpacaV2Oracle.sol

- Change oracle sanity check on AdminFacet
- obsolete version

[main][chore] Change oracle sanity check on AdminFacet

---

.mainnet.json

[main][chore] doge and ltc market address

---

.mainnet.json
script/deployments/AlpacaV2Oracle/config/SetTokenConfig.s.sol
script/deployments/MiniFL/config/SetPool.s.sol

[main][deploy] LTC and DOGE markets

---

.mainnet.json

[main][chore] update mainnet address

---

.mainnet.json

[main][chore] update address

---

.mainnet.json
.openzeppelin/unknown-56.json
deploy/core/facets/diamond-cut/execute-diamond.ts
deploy/core/upgrade/account-manager.ts
deploy/results/1686210985_upgrade_money_market_account_manager.json
script/deployments/MiniFL/config/SetPoolRewarders.s.sol
script/deployments/MoneyMarket/config/SetFlashloanParams.s.sol
script/deployments/MoneyMarket/config/SetTokenMaximumCapacities.s.sol
script/deployments/Rewarder/config/AddPool.s.sol
script/deployments/Rewarder/config/SetRewardPerSecond.s.sol

[main][chore] Increase THE and HIGH capacity

---

.mainnet.json

[main][chore] ada market address

---

script/BaseScript.sol
script/deployments/SwapHelper/config/SetSwapInfo.s.sol
script/deployments/SwapHelper/deploy/SwapHelper.s.sol
solidity/contracts/interfaces/ISwapHelper.sol
solidity/contracts/swap-helper/SwapHelper.sol
solidity/tests/swap-helper/SwapHelper.t.sol

- add SwapHelper contract
- to store swap calldata for modification

[main][feat] swap helper

---

script/deployments/SwapHelper/config/SetSwapInfo.s.sol
solidity/contracts/interfaces/ISwapHelper.sol
solidity/contracts/swap-helper/SwapHelper.sol
solidity/tests/swap-helper/SwapHelper.t.sol

- add `search` to get data offset
- automate offset finding when `setSwapInfo`

[main][feat] setSwapInfo helper

---

script/deployments/SwapHelper/config/SetSwapInfo.s.sol
solidity/contracts/interfaces/ISwapHelper.sol
solidity/contracts/swap-helper/SwapHelper.sol
solidity/tests/swap-helper/SwapHelper.t.sol

[main][feat] set slippage

---

solidity/contracts/money-market/facets/LiquidationFacet.sol
solidity/contracts/money-market/interfaces/ILiquidationFacet.sol
solidity/tests/money-market/liquidation/MoneyMarket_Liquidation_IbLiquidate.t.sol
solidity/tests/money-market/liquidation/MoneyMarket_Liquidation_Liquidate.t.sol

- LiquidationCall now accept the amount of collateral to liquidate
- To facilitate partial liquidation process instead of always full liquidate

[main][feat] Liquidate with specified amount

---

.mainnet.json
package.json
script/BaseScript.sol
script/deployments/SwapHelper/config/SetSwapInfoPancakeSwapV2.s.sol
script/deployments/SwapHelper/config/SetSwapInfoPancakeSwapV3.s.sol
script/deployments/SwapHelper/config/SetSwapInfoThenaFusion.s.sol
script/deployments/SwapHelper/config/SetSwapInfoThenaV1.s.sol
solidity/contracts/interfaces/IThenaRouterV2.sol
solidity/contracts/interfaces/IThenaRouterV3.sol
solidity/tests/swap-helper/SwapHelper_BaseFork.t.sol
solidity/tests/swap-helper/SwapHelper_GetSwapCalldata.t.sol

[main][chore] swap helper config script

---

script/deployments/SwapHelper/config/SetSwapInfoThenaV1.s.sol

[main][chore] update thena path helper

---

.mainnet.json
package.json
script/BaseScript.sol
script/deployments/SwapHelper/config/SetSwapInfoPancakeSwapV2.s.sol
script/deployments/SwapHelperIbLiquidationStrategy/deploy/SwapHelperIbLiquidationStrategy.s.sol

[main][chore] add variable and baseScript

---

README.md

[main][chore]: Update readme

---

.github/workflows/test-on-dispatch.yml
.github/workflows/test-on-push.yml
solidity/contracts/money-market/facets/BorrowFacet.sol
solidity/tests/money-market/over-collat/MoneyMarket_OverCollatBorrow_Borrow.t.sol

[main][fix] handle demote 2 token to isolate at once

---

.mainnet.json
package.json
script/BaseScript.sol
script/deployments/InterestModels/deploy/MMFlatSlopeModel1.s.sol
script/deployments/MoneyMarket/config/SetNonCollatBorrowerOk.s.sol
script/deployments/MoneyMarket/config/SetNonCollatInterestModel.s.sol
solidity/contracts/money-market/interest-models/MMFlatSlopeModel1.sol
solidity/tests/money-market/interest-models/MMFlatSlope1.t.sol

[main][feat] mm flat slop model

---

package.json
script/deployments/MoneyMarket/config/SetProtocolConfigs.s.sol

[main][feat] set protocol config script

---

foundry.toml
solidity/contracts/money-market/interfaces/IAdminFacet.sol
solidity/contracts/money-market/interfaces/IBorrowFacet.sol
solidity/contracts/money-market/interfaces/ICollateralFacet.sol
solidity/contracts/money-market/interfaces/IFeeModel.sol
solidity/contracts/money-market/interfaces/ILiquidationFacet.sol
solidity/contracts/money-market/interfaces/IMoneyMarket.sol
solidity/contracts/money-market/interfaces/INonCollatBorrowFacet.sol
solidity/contracts/money-market/interfaces/IViewFacet.sol
solidity/contracts/money-market/libraries/LibConstant.sol
solidity/contracts/money-market/libraries/LibDoublyLinkedList.sol

[main][chore] forward compile version

---

solidity/contracts/money-market/interfaces/ILendFacet.sol

[main][chore] lend facet pragma

---

.mainnet.json
package.json
script/BaseScript.sol
script/deployments/InterestModels/deploy/MMFlatSlopeModel2.s.sol
solidity/contracts/money-market/interest-models/MMFlatSlopeModel2.sol
solidity/tests/money-market/interest-models/MMFlatSlope2.t.sol

[main][feat] flat slope model2

---

deploy/config/accept-ownership.ts
deploy/core/accept-ownership.ts
package.json

- add accept ownership script (universal)

[main][chore] accept ownership script

---

deploy/core/facets/diamond-cut/execute-diamond.ts
package.json
script/deployments/MoneyMarket/deploy/BorrowFacet.s.sol

[main][feat] borrowFacet deployment script

---

solidity/contracts/account-manager/MoneyMarketAccountManager.sol
solidity/contracts/interfaces/IMoneyMarketAccountManager.sol
solidity/tests/money-market/account-manager/MoneyMarket_AccountManager.t.sol

[main][feat] mm account manager stakefor

---

.env.example
.mainnet.json
script/BaseScript.sol
script/deployments/ChainLinkOracle/config/SetPriceFeeds.s.sol
script/deployments/MoneyMarket/config/OpenMarket.s.sol
script/deployments/OracleMedianizer/config/SetMultiPrimarySources.s.sol

[main][feat] add wbeth token

---

deploy/core/facets/deploy/lend-facet.ts
deploy/file-helper.ts/config-file.helper.ts
package.json
solidity/contracts/money-market/facets/LendFacet.sol
solidity/contracts/money-market/interfaces/ILendFacet.sol
solidity/tests/money-market/lend/MoneyMarket_Lend_Deposit.t.sol
solidity/tests/money-market/lend/MoneyMarket_Lend_Withdraw.t.sol

[main][fix] tiny shares

---

solidity/contracts/money-market/facets/LendFacet.sol

[main][chore] optimize gas

---

deploy/exec/money-market/config/set-token-config.ts
package.json

[main][chore] set token config script
